
### Get all services
GET  http://localhost:3000/api/v1/tasks

### Create a new task
POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Description 1",
    "status": "pending"
}

### Update a task
PUT http://localhost:3000/api/v1/tasks/3
Content-Type: application/json

{
    "title": "Task 16",
    "description": "Description 16",
    "status": "completed"
}

### Delete a task
DELETE http://localhost:3000/api/v1/tasks/16